language: node_js
node_js: node
sudo: false
script:
- npm run test:ci
- npm run build
- |
  if [ "$TRAVIS_TEST_RESULT" == "0" ]; then
    npm run publish:autotag;
  fi
- |
  if [ "$TRAVIS_TEST_RESULT" == "0" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "x$TRAVIS_TAG" != "x" ]; then
    npm run publish:cdn;
  fi
env:
  global:
  # CDN_SECRET
  - secure: jLpBZ3uiiMuJRrSaEUWu8DQupnnsk8+KeaLMVCtft0XiQ2GtKacmoxY6hChyngnd0ry+xja4f4cFnCWjtSnaEEE199M8QTEUs603VFGs9GixD7N2vuJvNU+y/uJm6HpQzwncQTJq5IzTiRgMZ/418F5eiHUyDYbAi/hK9kaPZp5Me9hfD02IMMbgHxcvm3/zyKNZb5Mr0+lguvBhf6TCC+DG7I2LL1pjtqYHxEv2Gq2P95DPzx5bNEkmKsK3C/M2Dw9rMjGg74OMNVWmGcvdDPifdOm9TnjjOpyff/qe4ik4OEeGXONQLtVp0PtZnSRgHruhnhCqejkHiFHmDqMzrSSYj6fYghB4X3r2MlLFKEoH4fTmUgCFRVWqCO3WE3Je4T7Xy5QDBZmcamXVQXPEDL5c1Az2AKEFS8A5fxBU/z470cUt59NO6l5u1//HM6uAoAhSSHjEzHORinWJxqUF6gSlS9CnGH/cYK61zsUYMDY42+G297OmRdgUCAnQyUS6GPVMtnPVyuq6Vm9rkFxuEnkTVoSYEv8WXWwomnVxPXPaXt2BF4h32yIkwE7G45PThcrhAVKrUxZ6p0tg+ZTRhcE3+GzIJPRAzno3VXr0Xz3225oIAYgvDF6uIj9GHRoQB+VuQ1NR+Mr6NdtZGBqTtbtMYtyYCkcOGiUwmM4J0HA=
  # GITHUB_TOKEN
  - secure: f5gyHj1+IusUqeUtbSzJQodeGUJ2Xt7I10f5kudIGlfdmI3beUfRI5/jXsV2J8AEJj1jPPdp/PUsuTDOArptix4v/tdX8onc+3uVOGqjw32AS+wvFlnNTpO2ZDct42no4+HfFJ6Ix4ADagxyEc/z9/RbLK1ivmTzRTOvbtqp2Cko3giGXqj8uAPwxG3SpcuPPoaBqJREVt/fQB8HLze0rSS2eVjeUPPrs6+7KRrRGDuqqZulZJllxzwLY//yaZ+IboMdHsJBMGmmup95Yfm3U+WeHeaTddjvSZ948lifUylMiF5L+LqgkmJbsnJNAyKboYYjj2RVa3WW+VqsAO7f/v4kaUzVXZcGnY7dp4nZuky+aIsnQtxcDOn2tIOCvAICyz6P0Selc1ScHQF1ePKYjhXrg8PYFAX4QcvAF8i0CQypL8Hqzx/xEVSH6236ZRMdBe6ej28b8M7as8Vl59o7ttkiWCXcnZilNr1EYxsXHKkw5ZsC4f8XSOjLHBpCANWIoERKgcUCLueTLZfu2avAwYXUMRKi/7xxj3hvWusxGNz3Jm1zuCMBh7sqs/5T466Ht22D4hpWuML7rnBG2Nldk5nwVIQ2QYpiyd93YkI+FrB6nu3daxxYpUc0B0lpgE9FHvF5L01wrMjMbuKf9NfnfNukfsO05ahGSaKOxLTefZA=
  # RALLY_API_KEY
  - secure: 1ho2j85uC0umsDMyeG75yvS1KowpbYiWOXr/tiqatSw9dmQ4GkOf83jKuXibGFWuk26mCOQG78er+nADYXzU/55BNm1lWkPxK5aHMIsjhlJZHZEix9gDKzL6cBXts1/NQn7vNPxRNrvlP4NBcnXd7PvAPbGnbkWHznjFLll3CDj51sehk4JU8uOJoEGfv0q4C0Lbne+lAGBmWRcTwhJVci569h87NiTmjGzMhzrmyQ0vFP3AoPo/SmZ7rOfHhsdPaDkx5/7H80+o3Lrt87qospiJgAw80YFkdttPT3wYIrgSTIQFoHYB+zDScTy1a/LiHOXgVHI+3iLF6Oc4UJt+Z2qBflGcEU9gexQcSFJxSW1w5HYQZl/yPA48vulb2/p29vcu5Mf9FFzPAhAF1zb+FkxRewckF2u/0KFU85nlRH1awvWrUXf6OfKygUD/vSXJL9gPOqNUxwU2UYvhnfku2pT3YkJkGwi36dW7F4VnEEIrzGQ4aATy/OAP0UsiiH/A9RLeVkv9QlDPZ2i/dSOojzlOjIOJ3quhN+suW3dJiLL/Xn81hzLbIF+vnA0fDJnZMIowOxFUOlNhl2ONt2rs77IW6FtOm8l9rMwcIvk8MClBE13BjKXtrZREWdPIgk4l0RtdYj4EAgfv/bD7Oe813B5lEbwBr9Szfv4wmThlKSQ=
