# This workflow runs "npm i" to see if any BSI dependencies have updated.
# If so, it commits the package-lock changes and opens a PR if one does not already exist.

name: BSI Update

on:
  workflow_dispatch: # manual trigger for testing

jobs:
  build:
    # self-hosted doesn't work for public repos (security), so need to use ubuntu
    runs-on: ubuntu-latest

    timeout-minutes: 20

    env:
      BRANCH_NAME: ghworkflow/bsi_auto_update

    steps:
      - name: Checkout Repository
        uses: Brightspace/third-party-actions@actions/checkout

      - name: Use Node.js
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '12.x'

      - name: Checkout Branch
        run: git checkout $BRANCH_NAME || git checkout -b $BRANCH_NAME

      - name: Fresh Dependency Install
        run: npm install
      
      - name: Check For Changes
        id: check-changes
        run: echo "::set-output name=changes-exist::$(git diff -s --exit-code package-lock.json && echo false || echo true)"

      - name: Create Commit
        if: steps.check-changes.outputs.changes-exist
        run: |
          git reset --hard origin/master
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package-lock.json
          git commit -m 'BSI Auto Update Dependencies'
          git push --force --set-upstream origin $BRANCH_NAME

      - name: Create PR (if needed)
        id: create-pr
        if: steps.check-changes.outputs.changes-exist
        uses: Brightspace/third-party-actions@actions/github-script
        with:
          script: |
            const PRs = await github.pulls.list({
              owner: 'Brightspace',
              repo: 'brightspace-integration',
              head: 'refs/heads/${{ env.BRANCH_NAME }}',
              base: 'refs/heads/master'
            })
            if (PRs.length === 0) {
              const createPrResult = await github.pulls.create({
                owner: 'Brightspace',
                repo: 'brightspace-integration',
                title: 'Updating BSI Dependencies',
                head: 'refs/heads/${{ env.BRANCH_NAME }}',
                base: 'refs/heads/master'
              });
              github.issues.addLabels({
                owner: 'Brightspace',
                repo: 'brightspace-integration',
                issue_number: createPrResult.data.number,
                labels: ['auto-update']
              });
              return createPrResult.data.number;
            }
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
