# This workflow is just for testing
# fake edit to trigger sync 6
name: LMS Sync

on:
  push:
    branches:
      - US117758_bsisync

jobs:
  triggerSync:
    # self-hosted doesn't work for public repos (security), so need to use ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: Brightspace/third-party-actions@actions/checkout
    - name: Install dependencies
      run: sudo apt-get install -y curl jq
    - name: Get JWT
      id: get-jwt
      run: bash -e .github/workflows/scripts/get-jwt.sh
      env:
        BSI_SYNC_PEM: ${{ secrets.BSI_SYNC_PEM }}
    - name: Get App Token
      id: get-app-token
      run: bash -e .github/workflows/scripts/get-app-token.sh
      env:
        BSI_SYNC_JWT: ${{ steps.get-jwt.outputs.jwt }}
    - name: Repository Dispatch
      uses: Brightspace/third-party-actions@actions/github-script
      with:
        script: |
          github.repos.createDispatchEvent({
            owner: 'Brightspace',
            repo: 'lms',
            event_type: 'bsi-sync-test',
            client_payload: {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }
          });
        github-token: ${{ steps.get-app-token.outputs.token }}
